config/routes.rb
Rails.application.routes.draw do





 resources :salaries
 resources :products
 resources :bikes
 resources :mobiles  
 resources :shopes
 resources :students   
 resources :offices
 resources :bills
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/bike.rb
class Bike < ApplicationRecord
end

app/models/bill.rb
class Bill < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRec
end

app/models/electricity.rb
class Electricity < ApplicationRecord
end

app/models/mobile.rb
class Mobile < ApplicationRecord
end

app/models/office.rb
class Office < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/salary.rb
class Salary < ApplicationRecord
end

app/models/shope.rb
class Shope < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
end

app/controllers/mobiles_controller.rb
class MobilesController < ApplicationController
  def index
    @mobiles = Mobile.all
  end

  def new
    @mobile = Mobile.new
  end

  def create
    @mobiles = Mobile.create(mobile_params)

    redirect_to mobiles_path
  end

  def show
    @mobile = Mobile.find(params[:id])
  end

  def edit
    @mobile = Mobile.find(params[:id])  
  end

  def update
    @mobile = Mobile.find(params[:id])
    @mobile.update(mobile_params)

    redirect_to mobiles_path(@mobile)
  end

  def destroy
    @mobile = Mobile.find(params[:id])
    @mobile.destroy
  redirect_to mobiles_path
  end

  private
  
  def mobile_params
    params.require(:mobile).permit(:company, :model, :stroage)
end
end

app/helpers/bikes_helper.rb
module BikesHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/crud_helper.rb
module CrudHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/mobiles_helper.rb
module MobilesHelper
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/salaries_helper.rb
module SalariesHelper
end

app/helpers/shopes_helper.rb
module ShopesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/mobiles/edit.html.erb
<h3>Update Mobiles Details</h3>
<%= form_with model: @mobile do |form| %>
  <%= form.text_field :company, placeholder: "company" %>
  <%= form.text_field :model, placeholder: "model" %>
  <%= form.text_field :stroage, placeholder: "stroage" %>
  <%= form.submit %>
<% end %>

app/views/mobiles/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Company</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    <% @mobiles.each do |mob|%>
      <tr>
        <th scope="row">1</th>
        <td><%=  mob.company%></td>
        <td><%=  link_to "Edit",  edit_mobile_path(mob.id)%></td>
        <td><%=  link_to "Show", mobile_path(mob.id)%></td>
        <td><%=  button_to  'Delete', mobile_path(mob), method: 'delete' %></td>
    <% end%>
  </tbody>
</table>

app/views/mobiles/new.html.erb
<h1>Mobiles New</h1>
<%= form_for @mobile do |std| %>
  <%= std.text_field :company, placeholder: "company" %>
  <%= std.text_field :model, placeholder: "model" %>
  <%= std.text_field :stroage , placeholder: "stroage" %>
  <%= std.submit %>
<% end %>

app/views/mobiles/show.html.erb
<h1>Shopes</h1>
<table class="table table-striped table-dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Company</th>
      <th scope="col">Model</th>
      <th scope="col">Storage</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">#</th>
      <td><%= @mobile.company %></td>
      <td><%= @mobile.model %></td>
      <td><%= @mobile.stroage %></td>
    </tr>
  </tbody>
</table>