config/routes.rb
Rails.application.routes.draw do





 resources :salaries
 resources :products
 resources :bikes
 resources :mobiles  
 resources :shopes
 resources :students   
 resources :offices
 resources :bills
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/bike.rb
class Bike < ApplicationRecord
end

app/models/bill.rb
class Bill < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRec
end

app/models/electricity.rb
class Electricity < ApplicationRecord
end

app/models/mobile.rb
class Mobile < ApplicationRecord
end

app/models/office.rb
class Office < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/salary.rb
class Salary < ApplicationRecord
end

app/models/shope.rb
class Shope < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  def index
    @bills = Bill.all
  end

  def new
    @bill = Bill.new
  end

  def create 
    @bills = Bill.create(bill_params)

    redirect_to bills_path
  end

  def edit
    @bill = Bill.find(params[:id])
  end

  def update
    @bill = Bill.find(params[:id])
    @bill.update(bill_params)

    redirect_to bills_path(@bill)
  end

  def destroy
    @bill = Bill.find(params[:id])
    @bill.destroy
  redirect_to bills_path
  end

  def show
    @bill = Bill.find(params[:id])
  end

  private
  
  def bill_params
    params.require(:bill).permit(:product, :price, :total)
end

end

app/helpers/bikes_helper.rb
module BikesHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/crud_helper.rb
module CrudHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/mobiles_helper.rb
module MobilesHelper
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/salaries_helper.rb
module SalariesHelper
end

app/helpers/shopes_helper.rb
module ShopesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/bills/edit.html.erb
<h3>Update Bills Details</h3>
<%= form_with model: @bill do |form| %>
  <%= form.text_field :product, placeholder: "product" %>
  <%= form.text_field :price, placeholder: "price" %>
  <%= form.text_field :total, placeholder: "total" %>
  <%= form.submit %>
<% end %>

app/views/bills/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Product</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    <% @bills.each do |bil|%>
      <tr>
        <th scope="row">1</th>
        <td><%= bil.product%></td>
        <td><%=  link_to "Edit",  edit_bill_path(bil.id)%></td>
        <td><%=  link_to "Show", bill_path(bil.id)%></td>
        <td><%=  button_to  'Delete', bill_path(bil), method: 'delete' %></td>
    <% end%>
  </tbody>
</table>

app/views/bills/new.html.erb
<h1>Bill New</h1>
<%= form_for @bill do |form| %>
  <%= form.text_field :product, placeholder: "product" %>
  <%= form.text_field :price, placeholder: "price" %>
  <%= form.text_field :total, placeholder: "total" %>
  <%= form.submit %>
<% end %>

app/views/bills/show.html.erb
<h1>Shopes</h1>
<table class="table table-striped table-dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Product</th>
      <th scope="col">Price</th>
      <th scope="col">Total</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">#</th>
      <td><%= @bill.product %></td>
      <td><%= @bill.price %></td>
      <td><%= @bill.total %></td>
    </tr>
  </tbody>
</table>