config/routes.rb
Rails.application.routes.draw do





 resources :salaries
 resources :products
 resources :bikes
 resources :mobiles  
 resources :shopes
 resources :students   
 resources :offices
 resources :bills
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/bike.rb
class Bike < ApplicationRecord
end

app/models/bill.rb
class Bill < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRec
end

app/models/electricity.rb
class Electricity < ApplicationRecord
end

app/models/mobile.rb
class Mobile < ApplicationRecord
end

app/models/office.rb
class Office < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/salary.rb
class Salary < ApplicationRecord
end

app/models/shope.rb
class Shope < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
end

app/controllers/salaries_controller.rb
class SalariesController < ApplicationController
  def index
    @salaries = Salary.all
  end

  def edit
    @salary = Salary.find(params[:id])
  end

  def show
    @salary = Salary.find(params[:id])
  end

  def new
    @Salary = Salary.new
  end

  def create
    @salary = Salary.create(salary_params)

    redirect_to salaries_path
  end

  def update
    @salary = Salary.find(params[:id])
    @salary.update(salary_params)

    redirect_to salaries_path(@shope)
  end

  def destroy
    @salary = Salary.find(params[:id])
    @salary.destroy

    redirect_to salaries_path
  end



  private

  def salary_params
    params.require(:salary).permit(:labor, :group, :monthly_salary, :qualification)
  end
end

app/helpers/bikes_helper.rb
module BikesHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/crud_helper.rb
module CrudHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/mobiles_helper.rb
module MobilesHelper
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/salaries_helper.rb
module SalariesHelper
end

app/helpers/shopes_helper.rb
module ShopesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/salaries/edit.html.erb
<h1>Salaries#edit</h1>
<p>Find me in app/views/salaries/edit.html.erb</p>

app/views/salaries/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Labor</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    <% @salaries.each do |x|%>
      <tr>
        <th scope="row">1</th>
        <td><%= x.labor%></td>
        <td><%=  link_to "Edit",  edit_salary_path(x.id)%></td>
        <td><%=  link_to "Show", salary_path(x.id)%></td>
        <td><%=  link_to  'Delete', salary_path(x), method: 'delete' %></td>
    <% end%>
  </tbody>
</table>

app/views/salaries/new.html.erb
<h1>Salaries New</h1>
<%= form_for @salaries do |x| %>
  <%= form.text_field :labor, placeholder: "labor" %>
  <%= form.text_field :group, placeholder: "group" %>
  <%= form.text_field :monthly_salary, placeholder: "monthly_salary" %>
  <%= form.text_field :qualification, placeholder: "qualification" %>
  <%= form.submit %>
<% end %>

app/views/salaries/show.html.erb
<h1>Salaries</h1>
<table class="table table-striped table-dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Labor</th>
      <th scope="col">Group</th>
      <th scope="col">Monthly_salary</th>
      <th scope="col">Qualification</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td><%= @salary.labor %></td>
      <td><%= @salary.group %></td>
      <td><%= @salary.monthly_salary %></td>
      <td><%= @salary.qualification %></td>
    </tr>
  </tbody>
</table>