config/routes.rb
Rails.application.routes.draw do





 resources :salaries
 resources :products
 resources :bikes
 resources :mobiles  
 resources :shopes
 resources :students   
 resources :offices
 resources :bills
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/bike.rb
class Bike < ApplicationRecord
end

app/models/bill.rb
class Bill < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRec
end

app/models/electricity.rb
class Electricity < ApplicationRecord
end

app/models/mobile.rb
class Mobile < ApplicationRecord
end

app/models/office.rb
class Office < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/salary.rb
class Salary < ApplicationRecord
end

app/models/shope.rb
class Shope < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  def index
    @bikes = Bike.all
  end

  def new
    @bike = Bike.new
  end

  def create 
    @bikes = Bike.create(bike_params)

    redirect_to bikes_path
  end

  def edit
    @bike = Bike.find(params[:id])
  end

  def update 
    @bike = Bike.find(params[:id])
    @bike.update(bike_params)

    redirect_to bikes_path(@bike)
  end

  def show
    @bike = Bike.find(params[:id])
  end

  def destroy
    @bike = Bike.find(params[:id])
    @bike.destroy
  redirect_to bikes_path
  end

  private 
  
  def bike_params
    params.require(:bike).permit(:make, :year)
  end
end

app/helpers/bikes_helper.rb
module BikesHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/crud_helper.rb
module CrudHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/mobiles_helper.rb
module MobilesHelper
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/salaries_helper.rb
module SalariesHelper
end

app/helpers/shopes_helper.rb
module ShopesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/bikes/edit.html.erb
<h3>Update Bikes Details</h3>
<%= form_with model: @bike do |form| %>
  <%= form.text_field :make, placeholder: "make" %>
  <%= form.text_field :year, placeholder: "year" %>
  <%= form.submit %>
<% end %>

app/views/bikes/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Make</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    <% @bikes.each do |kk|%>
      <tr>
        <th scope="row">1</th>
        <td><%=  kk.make %></td>
        <td><%=  link_to "Edit",  edit_bike_path(kk.id)%></td>
        <td><%=  link_to "Show", bike_path(kk.id)%></td>
        <td><%=  button_to  'Delete', bike_path(kk), method: 'delete' %></td>
    <% end%>
  </tbody>
</table>

app/views/bikes/new.html.erb
<h1>Bikes New</h1>
<%= form_for @bike do |std| %>
  <%= std.text_field :make, placeholder: "make" %>
  <%= std.text_field :year, placeholder: "year" %>
  <%= std.submit %>
<% end %>

app/views/bikes/show.html.erb
<h1>Shopes</h1>
<table class="table table-striped table-dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Make</th>
      <th scope="col">Year</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">#</th>
      <td><%= @bike.make %></td>
      <td><%= @bike.year %></td>
    </tr>
  </tbody>
</table>